version: 2

sources:
  - name: raw
    description: "Source data for stock performance (Yahoo Finance) and VIX Volatility (FRED)."
    schema: raw
    
    tables:
      - name: stocks
        description: "Price performance data for a basket of stocks from Yahoo Finance (yFinance python package)."
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: vix
        description: "CBOE Volatility Index data from FRED"
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
